### ISSUE TITLE
413: Request Entity Too Large

### ISSUE THREAD

**Issue by bmiller59** [MainRo/deepspeech-server#1]
Thank you for this tool. I am getting a "413: Request Entity Too Large" message when I attempt to upload a file like this:

`curl -X POST --data-binary @zb.wav http://0.0.0.0:8000/stt`

The server is running and shows this message:
`config file: config, deepspeech.json
creating model /home/deepspeech/models/default/output_graph.pb /home/deepspeech/models/default/alphabet.txt
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
`

The file I am trying to post is 47692844 in size.

Would you consider adding to the configuration file a maximum file size to specify allowed?
It could also be convenient to allow the port to be set in the config.

Thank you.

**Comment by MainRo** [comment]
I need to check where the size limit come from. Your sample is somehow big bug it should work.

I agree for the port configuration. This is in the list of what I planed to do.

**Comment by MainRo** [comment]
I created issue #2 for the port configuration.

**Comment by bmiller59** [comment]
Thank you! This size limit is the bigger blocking issue for me. I appreciate it.
