### ISSUE TITLE
simple fixes to documentation: curl example and config file

### ISSUE THREAD

**Issue by rocket-pig** [MainRo/deepspeech-server#12]
Theyre both trivial fixes, and would save folks a useless hour digging around.

server defaults to 8080, not 8000. And putting brackets around the filename will get you an unintelligible error and server crash.  Should be:
`curl -X POST --data-binary @testing.wav http://localhost:8080/stt`

this config file would be a drop-in-and-use-immediately replacement for anyone who downloaded the supplied model from DeepSpeech project. there is no 'models.pb' file anywhere, as referenced by your documentation. and they end up un-tarring themselves to a 'models/' subdirectory.
```
{
  "deepspeech": {
    "model" :"models/output_graph.pb",
    "alphabet": "models/alphabet.txt",
    "lm": "models/lm.binary",
    "trie": "models/trie"
  },
  "server": {
    "http": {
      "request_max_size": 100048576
    }
  }
}

```
...save that as server.config in DeepSpeech/, 
cd DeepSpeech, 
deepspeech-server --config server.config 
and 'it just works'.

Thanks for your work, I was using a hackish FIFO scenario before to accomplish same thing, much improved.

**Comment by rocket-pig** [comment]
I changed the request_max_size to something larger than 1 MB (?) also.

**Comment by MainRo** [comment]
I kept the default request_max_size value because 1MB can contain 32s of audio (16Khz, 16bit), which should be enough for most cases.
