### ISSUE TITLE
Not working with deepspeech 0.2.0 

### ISSUE THREAD

**Issue by el-tocino** [MainRo/deepspeech-server#14]
Mozilla just released .2.0.  I've downloaded it, along with the new models, and verified that it works as expected with the deepspeech binaries. 

However, I'm getting an error when trying to start deepspeech-server (.6.0):

```
deepspeech-server  --config ../deepspeech/config.json 
Traceback (most recent call last):
  File "/usr/local/bin/deepspeech-server", line 3, in <module>
    from deepspeech_server.server import main;
  File "/usr/local/lib/python3.6/dist-packages/deepspeech_server/server.py", line 16, in <module>
    import deepspeech_server.deepspeech as deepspeech
  File "/usr/local/lib/python3.6/dist-packages/deepspeech_server/deepspeech.py", line 9, in <module>
    from deepspeech.model import Model
ModuleNotFoundError: No module named 'deepspeech.model'
```

deepspeech.model no longer appears to be valid under .2.0:

```
python3
>>> from deepspeech.model import Model
ModuleNotFoundError: No module named 'deepspeech.model'
```

I've removed and reinstalled both deepspeech and deepspeech-server to no avail.

**Comment by MainRo** [comment]
The Model object is now directly in the deepspeech module. I will fix this.

**Comment by johanpalmqvist** [comment]
I got it working with this patch:
[deepspeech-server.diff.txt](https://github.com/MainRo/deepspeech-server/files/2407197/deepspeech-server.diff.txt)

**Comment by el-tocino** [comment]
I applied @johanpalmqvist's patch, and it works for me as well.  Thanks!

**Comment by MainRo** [comment]
re-opening until fixed in this repo.
