### ISSUE TITLE
move model parameters to the configuration file

### ISSUE THREAD

**Issue by MainRo** [MainRo/deepspeech-server#15]
The following parameters are currently hard coded in the deepspeech driver:

- N_FEATURES = 26
- N_CONTEXT = 9
- BEAM_WIDTH = 500
- LM_WEIGHT = 1.75
- WORD_COUNT_WEIGHT = 1.00
- VALID_WORD_COUNT_WEIGHT = 1.00

They should be set in the configuration file.

**Comment by olafthiele** [comment]
Do you know where I can find these values? Seems like they are different for the current release.

Thanks

**Comment by MainRo** [comment]
It seems that lm_weight and vcw_weight  have been removed. I will look at this.

**Comment by MainRo** [comment]
closing this issue and tracking this in #19.
