### ISSUE TITLE
Use the streaming inference API to improve inference speed

### ISSUE THREAD

**Issue by MainRo** [MainRo/deepspeech-server#16]
DeepSpeech v 0.2 implements a streaming API to execute inference while data arrives. This avoid waiting for the complete data before doing the inference, and should be faster. A code snippet is available here:

https://gist.github.com/reuben/80d64de15d1f46d34d28c7e83fc5f57e#file-ds_mic-py

**Comment by poohsen** [comment]
did you by any chance think on how this could work @MainRo ? 

I have this working without an http server, just some quick & dirty code taken from [a medium article](https://scgupta.medium.com/how-to-build-python-transcriber-using-mozilla-deepspeech-5485b8d234cf) where chunks of audio are read from a microphone. Not much experience with streaming over http but it sounds like a fun project to look into. If you gave this some thought already and have some pointers for what might need changing, I'd love to hear it.

**Comment by MainRo** [comment]
AFAIR the python deepspeech API for this was quite straightforward. However, there was more work on the deepspeech-server part so that the HTTP requests data is read In several steps.
