### ISSUE TITLE
Requested audio file name in logs

### ISSUE THREAD

**Issue by krupalkp97** [MainRo/deepspeech-server#24]
Hey romain picard,
First of all thanks for the deepspeech server, i wanted to use it as production
server and i want the audio file name in the logs as well along with STT result . I am kind of new at server side programing and api integration , so can you guide me how to show the requested audio file name along with STT result .

i have tried to log the `item.data` in the deepspeech.py along with STT result log but i think it's the stream to data. 

one more quick question how can i reduce the response time right now it's taking 4-5 seconds(on cpu). can deepspeech-gpu make any difference?  

Thanks

**Comment by MainRo** [comment]
On the server side, there is no notion of filename: the client sends
some data to the server; it can be a file or  a microphone data. If you
need such a thing, the file name could be added in a http header, and
retrieved on the server side.

Running the model on a GPU will be faster for sure, but also more
expensive. If you train your own model, you can also quantize it: It
will speed up the model inference time a lot, and reduce a little bit
its performances. There used to be some tools in the deepspeech
repository for this. They may be still present in it.

**Comment by krupalkp97** [comment]
Hey @MainRo ,
Thanks for the quick answer i will try the following suggestion.
