### ISSUE TITLE
Add authorization/authentication support

### ISSUE THREAD

**Issue by MainRo** [MainRo/deepspeech-server#3]
An authentication support is needed to serve deepspeech on a public server without letting anybody using it. It should be based on a plugin system using external modules. This would allow anyone to use its own authentication system/backend.

**Comment by SuperKogito** [comment]
Hello @MainRo, 
Thank you for the nice code!
Is there any progress regarding this? or an example/ tutorial that one can follow/ start with ?

**Comment by MainRo** [comment]
No there is no progress on this issue. Since deepspeech is now dead, I do not really work on this project anymore.
