### ISSUE TITLE
How to run as a background service?

### ISSUE THREAD

**Issue by Fellhahn** [MainRo/deepspeech-server#32]
Hi,

Apologies; I am not a programmer.

How can I get this program to run as a background service (on Ubuntu 18.04) that will run at system startup and always be listening?

It run from the console just fine but has to be left open, as soon as I send ctrl+c the listening server shuts down.

**Comment by MainRo** [comment]
on ubuntu, you can create a systemd service and enable it. it will then start on system startup. You can also use docker-compose.
