### ISSUE TITLE
Concurrent Requests

### ISSUE THREAD

**Issue by bandiphani** [MainRo/deepspeech-server#39]
Hi... 
Is this API will allow concurrent requests? if yes how many simultaneous requests I can make through this API? Is it depends on hosted server configuration(no of CPU and GUPU) and bandwidth? 

Regards,
Phaneendra.

**Comment by MainRo** [comment]
The http server is asynchronous, but each request is executed in the context of the main loop. So each prediction will block the processing of another request until completed. If you need to parallelize requests, you have to start several instances of the server. 
A somehow simple way to do this is probably to start multiple instances of the docker image (https://github.com/MainRo/docker-deepspeech-server) with docker compose, and use a reverse proxy like traefik.

**Comment by bandiphani** [comment]
> The http server is asynchronous, but each request is executed in the context of the main loop. So each prediction will block the processing of another request until completed. If you need to parallelize requests, you have to start several instances of the server.
> A somehow simple way to do this is probably to start multiple instances of the docker image (https://github.com/MainRo/docker-deepspeech-server) with docker compose, and use a reverse proxy like traefik.

Thanks..
