### ISSUE TITLE
Response mimetype "application/octet-stream"

### ISSUE THREAD

**Issue by ChrisB85** [MainRo/deepspeech-server#40]
Hi,

I'm trying to use deepspeech-server with Rhasspy via Speech To Text Remote HTTP module, but the problem is that deepspeech-server response mimetype is "application/octet-stream" instead of "application/json":

`[ERROR:2021-06-15 21:37:15,270] rhasspyremote_http_hermes: handle_stop_listening
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-remote-http-hermes/rhasspyremote_http_hermes/__init__.py", line 606, in handle_stop_listening
    transcription_dict = await response.json()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://192.168.0.6:7123/stt?siteId=kitchen')`

I think "application/octet-stream" is wrong mimetype for text response, so maybe that should be changed?

**Comment by MainRo** [comment]
Yes, you are right. The correct mime type should probably be "text/plain".

**Comment by MainRo** [comment]
There is an existing option in the http server library to provide specific headers. I made the change, tell me if it is ok.
