### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by haowaiwai** [MainRo/deepspeech-server#43]
deepspeech-server --config config.yaml
http sink error: 'Observable' object has no attribute 'subscribe_', NoneType: None

What's the problem, thanks

**Comment by MainRo** [comment]
I am currently upgrading some dependencies of deepspeech-server causing such issues. You can try to downgrade them:

pip install cyclotron~=1.2 cyclotron-aiohttp~=1.0 cyclotron-std~=1.0

you probably have v2 for each of them.

**Comment by haowaiwai** [comment]
It's solved, thank you
