### ISSUE TITLE
Document python version required (support for async def etc.)

### ISSUE THREAD

**Issue by nealmcb** [MainRo/deepspeech-server#5]
I get this error, presumably because `async def` is not in Python 3.4:
```
..../deepspeech/lib/python3.4/site-packages/deepspeech_server/driver/http_driver.py", line 20
    async def on_post_data(request, path):
            ^
SyntaxError: invalid syntax
```
The `README.md` and `setup.py` files should indicate which version of Python is required.

**Comment by MainRo** [comment]
Yes python 3.5 is the minimal required version for now. I will document this. 
If this is an issue for a lot of people I may replace them with "yield/coroutine" so that python 3.4 is supported.

**Comment by nealmcb** [comment]
Cool - thanks for using the setup.py `python-requires` too ;)
