### ISSUE TITLE
HTTP response not working

### ISSUE THREAD

**Issue by marymirzaei** [MainRo/deepspeech-server#8]
I have tried to retrieve the transcription of a test wav file from a python script. The console of the server is working properly, showing the transcript, however, I couldn't get the transcript as the HTTP response and the server terminal displayed the following runtime warning: **RuntimeWarning: coroutine 'StreamResponse.write' was never awaited
  response.write(bytearray(i["data"], 'utf8'))**

```
======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
console: experience proves this
/Users/lapwing/anaconda2/envs/ds2/lib/python3.6/site-packages/deepspeech_server/driver/http_driver.py:37: RuntimeWarning: coroutine 'StreamResponse.write' was never awaited
  response.write(bytearray(i["data"], 'utf8'))
console: experience proves this
```

I am using
Deepspeech version 0.1.1
Deepspeech-server version 0.4.0
and here is the code that I have used to query the server:
```
import os
import urllib2
class EnhancedFile(file):
    def __init__(self, *args, **keyws):
        file.__init__(self, *args, **keyws)
    def __len__(self):
        return int(os.fstat(self.fileno())[6])
theFile = EnhancedFile('test1.wav', 'r')
theUrl = "http://127.0.0.1:8080/stt"
theHeaders= {'Content-Type': 'text/xml'}
theRequest = urllib2.Request(theUrl, theFile, theHeaders)
response = urllib2.urlopen(theRequest)
theFile.close()
for line in response:
    print line
```
similar problem with the sample curl command:
`curl -X POST --data-binary @test1.wav http://127.0.0.1:8080/stt`

**Comment by MainRo** [comment]
This is probably because the http response is acknowledged before aiohttp could schedule the await on the request future. Can you try with deepspeech 0.1.0 ? The behavior difference may come from the changes in the python bindings (not more hold of the GIL).

**Comment by domenicrosati** [comment]
Tried `curl  -X POST --data-binary @test_files/hello_world.wav http://localhost:8080/stt` with deepspeech 0.1.0 and confirmed that it throws `/usr/local/lib/python3.6/site-packages/deepspeech_server/driver/http_driver.py:37: RuntimeWarning: coroutine 'StreamResponse.write' was never awaited
  response.write(bytearray(i["data"], 'utf8'))`

**Comment by domenicrosati** [comment]
I am not exactly familiar with aiohttp, but it looks like you are trying to write to a stream outside of the context of a couroutine which is causing the problem. I don't think this can be done?

**Comment by MainRo** [comment]
I reproduced it on another machine. looking at this...
