### ISSUE TITLE
Auto publish PyPi

### ISSUE THREAD

**Issue by madhavajay** [MainRo/deepspeech-server#9]
Awesome project. Any chance you could setup auto pushing new releases to pypi? 👍 
0.4.1 fixes a bug which makes it more functional again but the PyPi only has 0.4

**Comment by MainRo** [comment]
I just push the new release.
Good point to automate this. This is something I never did. 
I suppose that this requires to generate the package via a CI tool, and then publish it to pypi from the CI ?

**Comment by madhavajay** [comment]
Yeah there are some guides if you google, main thing is keeping any secrets out of the repo, maybe use an .env file and source it if it exists in a bash script or something. I assume theres a good flow for doing this since others must be doing it.

**Comment by fabianvf** [comment]
Travis ci supports auto-publish to pypi using encrypted credentials, here's one of my projects that automatically deploys on tagged commits to master:

https://github.com/fabianvf/python-rake/blob/master/.travis.yml#L16

Travis docs:
https://docs.travis-ci.com/user/deployment/pypi/
